// Dữ liệu mẫu cho website VietMart
const categories = [
    { id: 1, name: "Gạo & Ngũ cốc", icon: "fas fa-seedling", slug: "gao-ngu-coc" },
    { id: 2, name: "Dầu ăn", icon: "fas fa-oil-can", slug: "dau-an" },
    { id: 3, name: "Gia vị", icon: "fas fa-pepper-hot", slug: "gia-vi" },
    { id: 4, name: "Nước mắm", icon: "fas fa-wine-bottle", slug: "nuoc-mam" },
    { id: 5, name: "Đồ gia dụng", icon: "fas fa-utensils", slug: "do-gia-dung" },
    { id: 6, name: "Thực phẩm tươi", icon: "fas fa-apple-alt", slug: "thuc-pham-tuoi" },
    { id: 7, name: "Bánh kẹo", icon: "fas fa-cookie-bite", slug: "banh-keo" },
];

const products = [
    // Flash Sale Products
    {
        id: 1,
        name: "Gạo thơm Jasmine 5kg",
        description: "Gạo thơm Jasmine cao cấp, hạt dài, thơm ngon",
        price: 135000,
        originalPrice: 200000,
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 1,
        isFlashSale: true,
        isNew: false,
        isBestSeller: false,
        discountPercent: 32,
        soldCount: 234,
        rating: 5.0,
        stock: 100,
    },
    {
        id: 2,
        name: "Dầu ăn cao cấp 1L",
        description: "Dầu ăn tinh luyện cao cấp, an toàn cho sức khỏe",
        price: 28000,
        originalPrice: 42000,
        image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 2,
        isFlashSale: true,
        isNew: false,
        isBestSeller: false,
        discountPercent: 33,
        soldCount: 89,
        rating: 4.5,
        stock: 75,
    },
    {
        id: 3,
        name: "Nước mắm Phú Quốc 500ml",
        description: "Nước mắm truyền thống Phú Quốc, đậm đà hương vị",
        price: 45000,
        originalPrice: 65000,
        image: "https://images.unsplash.com/photo-1518843875459-f738682238a6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 4,
        isFlashSale: true,
        isNew: false,
        isBestSeller: false,
        discountPercent: 31,
        soldCount: 156,
        rating: 4.8,
        stock: 50,
    },
    {
        id: 4,
        name: "Mì tôm thùng 30 gói",
        description: "Mì tôm chua cay thùng 30 gói tiện lợi",
        price: 118000,
        originalPrice: 150000,
        image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 7,
        isFlashSale: true,
        isNew: false,
        isBestSeller: false,
        discountPercent: 21,
        soldCount: 312,
        rating: 4.2,
        stock: 200,
    },
    {
        id: 5,
        name: "Cà phê Trung Nguyên 500g",
        description: "Cà phê rang xay Trung Nguyên nguyên chất",
        price: 95000,
        originalPrice: 125000,
        image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 7,
        isFlashSale: true,
        isNew: false,
        isBestSeller: false,
        discountPercent: 24,
        soldCount: 178,
        rating: 4.7,
        stock: 60,
    },
    
    // New Products
    {
        id: 6,
        name: "Tương ớt Chin-su 270g",
        description: "Tương ớt Chin-su cay ngọt đậm đà",
        price: 24500,
        originalPrice: 29000,
        image: "https://images.unsplash.com/photo-1599493758267-c6c884c7071f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 3,
        isFlashSale: false,
        isNew: true,
        isBestSeller: false,
        discountPercent: 15,
        soldCount: 45,
        rating: 5.0,
        stock: 80,
    },
    {
        id: 7,
        name: "Phở khô Vifon thùng 30 gói",
        description: "Phở khô Vifon thơm ngon, tiện lợi",
        price: 165000,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 7,
        isFlashSale: false,
        isNew: true,
        isBestSeller: false,
        discountPercent: 0,
        soldCount: 23,
        rating: 4.0,
        stock: 150,
    },
    {
        id: 8,
        name: "Nước mắm Cá Cơm 650ml",
        description: "Nước mắm cá cơm nguyên chất, thơm ngon",
        price: 52000,
        originalPrice: 58000,
        image: "https://images.unsplash.com/photo-1518843875459-f738682238a6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 4,
        isFlashSale: false,
        isNew: true,
        isBestSeller: false,
        discountPercent: 10,
        soldCount: 67,
        rating: 5.0,
        stock: 90,
    },
    {
        id: 9,
        name: "Gạo nếp cẩm 1kg",
        description: "Gạo nếp cẩm tím nguyên chất, bổ dưỡng",
        price: 38000,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 1,
        isFlashSale: false,
        isNew: true,
        isBestSeller: false,
        discountPercent: 0,
        soldCount: 34,
        rating: 4.0,
        stock: 70,
    },
    
    // Best Sellers
    {
        id: 10,
        name: "Cà phê G7 3in1 hộp 21 gói",
        description: "Cà phê G7 3in1 thơm ngon, tiện lợi",
        price: 58000,
        originalPrice: 65000,
        image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 7,
        isFlashSale: false,
        isNew: false,
        isBestSeller: true,
        discountPercent: 11,
        soldCount: 1200,
        rating: 4.8,
        stock: 300,
    },
    {
        id: 11,
        name: "Dầu hào Lee Kum Kee 510g",
        description: "Dầu hào Lee Kum Kee đậm đà, ngon cơm",
        price: 42000,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1599493758267-c6c884c7071f?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 3,
        isFlashSale: false,
        isNew: false,
        isBestSeller: true,
        discountPercent: 0,
        soldCount: 856,
        rating: 4.7,
        stock: 180,
    },
    {
        id: 12,
        name: "Bún tươi Thuận Phát 500g",
        description: "Bún tươi Thuận Phát dai ngon, tươi sạch",
        price: 12000,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 6,
        isFlashSale: false,
        isNew: false,
        isBestSeller: true,
        discountPercent: 0,
        soldCount: 643,
        rating: 4.5,
        stock: 250,
    },
    {
        id: 13,
        name: "Me chua Phú Gia 200g",
        description: "Me chua Phú Gia chua ngọt, thanh mát",
        price: 15500,
        originalPrice: 18000,
        image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 6,
        isFlashSale: false,
        isNew: false,
        isBestSeller: true,
        discountPercent: 14,
        soldCount: 421,
        rating: 4.3,
        stock: 160,
    },
    
    // Rice Products
    {
        id: 14,
        name: "Gạo Jasmine Hạt Ngọc Trời 5kg",
        description: "Gạo Jasmine cao cấp hạt ngọc trời thơm dẻo",
        price: 145000,
        originalPrice: 165000,
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 1,
        isFlashSale: false,
        isNew: false,
        isBestSeller: false,
        discountPercent: 12,
        soldCount: 345,
        rating: 5.0,
        stock: 120,
    },
    {
        id: 15,
        name: "Gạo lứt hữu cơ 2kg",
        description: "Gạo lứt hữu cơ sạch, bổ dưỡng",
        price: 78000,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1528736235302-52922df5c122?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 1,
        isFlashSale: false,
        isNew: false,
        isBestSeller: false,
        discountPercent: 0,
        soldCount: 123,
        rating: 4.0,
        stock: 90,
    },
    {
        id: 16,
        name: "Ngũ cốc dinh dưỡng 500g",
        description: "Ngũ cốc dinh dưỡng tổng hợp nhiều loại hạt",
        price: 45000,
        originalPrice: 52000,
        image: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 1,
        isFlashSale: false,
        isNew: false,
        isBestSeller: false,
        discountPercent: 13,
        soldCount: 234,
        rating: 5.0,
        stock: 150,
    },
    {
        id: 17,
        name: "Gạo nếp than 1kg",
        description: "Gạo nếp than đặc sản, dẻo thơm",
        price: 42000,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 1,
        isFlashSale: false,
        isNew: false,
        isBestSeller: false,
        discountPercent: 0,
        soldCount: 87,
        rating: 4.0,
        stock: 70,
    },
    {
        id: 18,
        name: "Tấm thơm Sài Gòn 5kg",
        description: "Tấm thơm Sài Gòn truyền thống miền Nam",
        price: 115000,
        originalPrice: 125000,
        image: "https://images.unsplash.com/photo-1516684669134-de6f7c473a2a?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
        categoryId: 1,
        isFlashSale: false,
        isNew: false,
        isBestSeller: false,
        discountPercent: 8,
        soldCount: 456,
        rating: 5.0,
        stock: 200,
    }
];